# ===========================
# DATABASE CONFIG
# ===========================

# MySQL database URL
spring.datasource.url=jdbc:mysql://localhost:3306/smarthire_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# MySQL username (default root)
spring.datasource.username=root

# MySQL password - apna password yahan likho
spring.datasource.password=aNKIT@1704

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===========================
# JPA / HIBERNATE
# ===========================

# update = tables auto create/update ho jayengi
spring.jpa.hibernate.ddl-auto=update

# SQL queries terminal mein dikhegi
spring.jpa.show-sql=true

# MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===========================
# THYMELEAF
# ===========================

# Cache off - development mein changes turant dikhenge
spring.thymeleaf.cache=false


# ===========================
# FILE UPLOAD
# ===========================

# Max resume file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Folder jahan resume save hoga
file.upload-dir=uploads/resumes


# ===========================
# SERVER
# ===========================

# App is port pe chalegi
server.port=8080

spring.main.allow-circular-references=true